// auth
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const REFRESH_TOKEN_PENDING = 'REFRESH_TOKEN_PENDING';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';

// flash messages
export const SHOW_FLASH_MESSAGES = 'SHOW_FLASH_MESSAGES';
export const HIDE_FLASH_MESSAGES = 'HIDE_FLASH_MESSAGES';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const CLEAR_FLASH_MESSAGES = 'CLEAR_FLASH_MESSAGES';
export const CHANGE_FLASH_MESSAGE_STATUS = 'CHANGE_FLASH_MESSAGE_STATUS';

// friends
export const STORE_FRIENDS = 'STORE_FRIENDS';
export const FETCH_FRIENDS_PENDING = 'FETCH_FRIENDS_PENDING';
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_FAIL = 'FETCH_FRIENDS_FAIL';
export const REQUEST_FRIENDSHIP_PENDING = 'REQUEST_FRIENDSHIP_PENDING';
export const REQUEST_FRIENDSHIP_SUCCESS = 'REQUEST_FRIENDSHIP_SUCCESS';
export const REQUEST_FRIENDSHIP_FAIL = 'REQUEST_FRIENDSHIP_FAIL';
