// auth
export const REGISTER_PENDING = 'REGISTER_PENDING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_PENDING = 'LOGOUT_PENDING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const REFRESH_TOKEN_PENDING = 'REFRESH_TOKEN_PENDING'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL'

// flash messages
export const SHOW_FLASH = 'SHOW_FLASH'
export const HIDE_FLASH = 'HIDE_FLASH'
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const RESET_FLASH = 'RESET_FLASH'
export const CHANGE_FLASH_STATUS = 'CHANGE_FLASH_STATUS'

// relationships
export const STORE_RELATIONSHIPS = 'STORE_RELATIONSHIPS'
export const FETCH_RELATIONSHIPS_PENDING = 'FETCH_RELATIONSHIPS_PENDING'
export const FETCH_RELATIONSHIPS_SUCCESS = 'FETCH_RELATIONSHIPS_SUCCESS'
export const FETCH_RELATIONSHIPS_FAIL = 'FETCH_RELATIONSHIPS_FAIL'
export const REQUEST_FRIENDSHIP_PENDING = 'REQUEST_FRIENDSHIP_PENDING'
export const REQUEST_FRIENDSHIP_SUCCESS = 'REQUEST_FRIENDSHIP_SUCCESS'
export const REQUEST_FRIENDSHIP_FAIL = 'REQUEST_FRIENDSHIP_FAIL'

// profile
export const STORE_PROFILE = 'STORE_PROFILE'
export const FETCH_PROFILE_PENDING = 'FETCH_PROFILE_PENDING'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

// users
export const STORE_USER = 'STORE_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_PENDING = 'FETCH_USER_PENDING'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_PENDING= 'UPDATE_USER_PENDING'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

// messages
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const REFRESH_USERS = 'REFRESH_USERS'
export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL'
export const JOIN_CHANNEL = 'JOIN_CHANNEL'
export const LEAVE_CHANNEL = 'LEAVE_CHANNEL'
export const LOAD_MESSAGES = 'LOAD_MESSAGES'
export const LOAD_MESSAGES_PENDING = 'LOAD_MESSAGES_PENDING'
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL'

// chat
export const CREATE_PRIVATE_CHAT = 'CREATE_PRIVATE_CHAT'
export const RESET_UNREAD_MESSAGES = 'RESET_UNREAD_MESSAGES'
export const SAVE_DOCUMENT_TITLE = 'SAVE_DOCUMENT_TITLE'

export const SEND_PUBLIC_KEY = 'SEND_PUBLIC_KEY'
export const RECEIVE_PUBLIC_KEY = 'RECEIVE_PUBLIC_KEY'
export const UPDATE_CHANNEL_KEYS = 'UPDATE_CHANNEL_KEYS'
